jupyterhub:
  auth:
    github:
      org_whitelist:
        -  dirac-institute
        -  lsst-sqre
        -  pangeo-data
        -  dask
        -  xarray-dev
        -  jupyterhub
        -  informatics-lab
        -  pydata
        -  astropy
        -  sunpy
    admin:
      access: true
      users:
        - mrocklin
        - jhamman
        - rabernat
        - yuvipanda
        - choldgraf
        - jacobtomlinson
        - dsludwig
  singleuser:
    cloudMetadata:
      enabled: true
    cpu:
      limit: 4
      guarantee: 1
    memory:
      limit: 14G
      guarantee: 4G
